from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[1]

DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
MONTHLY_BATCH_DIR = DATA_DIR / "monthly_batches"
REPORTS_DIR = DATA_DIR / "reports"

MODEL_DIR = BASE_DIR / "models"

RAW_DATA_PATH = RAW_DATA_DIR / "accepted_2007_to_2018Q4.csv"
PROCESSED_DATA_PATH = PROCESSED_DATA_DIR / "processed_lending_club.csv"

CHAMPION_MODEL_PATH = MODEL_DIR / "champion_model.pkl"
CHALLENGER_MODEL_PATH = MODEL_DIR / "challenger_model.pkl"
LEGACY_MODEL_PATH = MODEL_DIR / "lightgbm_credit_risk_pipeline.pkl"

TARGET_COLUMN = "target"
DATE_COLUMN = "issue_d"

RANDOM_STATE = 42

REFERENCE_DATA_END_DATE = "2016-01-01"

VALIDATION_START_DATE = "2016-01-01"
VALIDATION_END_DATE = "2017-01-01"

HOLDOUT_START_DATE = "2017-01-01"
HOLDOUT_END_DATE = "2018-01-01"

CURRENT_DATA_START_DATE = "2018-01-01"
CURRENT_DATA_END_DATE = "2019-01-01"

DRIFT_REFERENCE_END_DATE = REFERENCE_DATA_END_DATE
DRIFT_CURRENT_START_DATE = CURRENT_DATA_START_DATE
DRIFT_CURRENT_END_DATE = CURRENT_DATA_END_DATE

RETRAINING_TRAIN_START_DATE = "2012-01-01"
RETRAINING_TRAIN_END_DATE = HOLDOUT_END_DATE

DRIFT_THRESHOLD = 0.30

MAX_PR_AUC_DROP_ALLOWED = 0.02
MAX_ROC_AUC_DROP_ALLOWED = 0.02
MIN_RECALL_IMPROVEMENT = 0.00

MAX_TRAIN_ROWS = 300_000
MAX_VALIDATION_ROWS = 100_000
MAX_REFERENCE_ROWS = 50_000
MAX_CURRENT_ROWS = 50_000
MAX_HOLDOUT_ROWS = 100_000
MAX_EVALUATION_ROWS = 100_000

TRAIN_SAMPLE_ROWS = MAX_TRAIN_ROWS
VALIDATION_SAMPLE_ROWS = MAX_VALIDATION_ROWS

REFERENCE_SAMPLE_ROWS = MAX_REFERENCE_ROWS
CURRENT_SAMPLE_ROWS = MAX_CURRENT_ROWS

DRIFT_SAMPLE_ROWS = MAX_REFERENCE_ROWS
HOLDOUT_SAMPLE_ROWS = MAX_HOLDOUT_ROWS
EVALUATION_SAMPLE_ROWS = MAX_EVALUATION_ROWS